### ISSUE TITLE
how to clean browser css cache

### ISSUE THREAD

**Issue by hank7444** [zeit/next-plugins#11]
Hi @timneutkens 

`
In production the stylesheet is compiled to .next/static/style.css. You have to include it into the page using either next/head or a custom _document.js. The file will be served from /_next/static/style.css
`

usually we will use hash code to clean browser cache if css file has any modification, like style.41d523.css

how can we do this on this plugin?

**Comment by Ehesp** [comment]
I ended up doing the following in `_document.js` - this works for the time being, however we need to make sure the BUILD_ID is the same on a multi-deployment basis!

```
import Document, { Head, Main, NextScript } from 'next/document';
import { readFileSync } from 'fs';

let version = '';

if (process.env.NODE_ENV === 'production') {
  version = `?v=${readFileSync(`${process.cwd()}/src/.next/BUILD_ID`)}`;
}

export default class extends Document {
  render() {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href={`/_next/static/style.css${version}`} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

**Comment by kachkaev** [comment]
It's also possible to use file's hash instead of `BUILD_ID` as version:

```js
import { createHash } from "crypto";
import { readFileSync } from "fs";

// ...

let version = "";
if (process.env.NODE_ENV === "production") {
  const hash = createHash("sha256");
  hash.update(readFileSync(`${process.cwd()}/.next/static/style.css`));
  version = `?v=${hash.digest("hex").substr(0, 8)}`;
}

// ...
```

If the styles don't change between builds, there's no need to download them and everyone is better off.

In general, it's more efficient to calculate file cache using streams, but this should be unnecessary in our case. if `.next/static/style.css` is big enough to slow down the server setup, something is probably wrong 😃 

[`crypto.createHash`](https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm_options) has been a part of Node's core nearly since the beginning of times, so there is no need to install a new module.

**Comment by kachkaev** [comment]
Even though the workarounds in two previous comments fix the issue with `style.css` caching, all other static assets like images remain under over-cache thread. It'd be great to bring some webpack magic here, which would not only allow correct caching, but also storing images in folders with components (now these have to go to `static`, which separates them from a place where they belong.

**Comment by kachkaev** [comment]
Here's one more discovery that might have those who have little CSS in `style.css`. This is the case when the majority of styles comes from [styled-components](https://www.styled-components.com/) or a similar framework. Turns out you can improve your website's performance by including the contents of `static/styles.css` directly into document, e.g. like this:

```js
let style = "";
if (process.env.NODE_ENV === "production") {
  style = fs.readFileSync(`${process.cwd()}/.next/static/style.css`, "utf8");
}

// inside _document's Head:
{style ? (
<style>{style}</style>
) : (
<link rel="stylesheet" href="/_next/static/style.css" />
)}
```

This helped me change my [lighthouse](https://developers.google.com/web/tools/lighthouse/) performance score in production from 89 to 96 because _First meaningful paint_ time decreased from 2.06 to 1.10 seconds. This is a warning in the original report that I followed:

<img width="573" alt="screen shot 2018-03-26 at 11 31 08" src="https://user-images.githubusercontent.com/608862/37901923-b0cfc1ea-30ea-11e8-86f1-22445f717eba.png">
 
When a stylesheet is heavy, it's cheaper to load it as a separate file and cache it aggressively, thus offloading the size of your HTMLs while avoiding extra round trips in consequent page requests. However, when `style.css` just is [normalize.css](https://necolas.github.io/normalize.css/) and a couple of simple global selectors, always keeping the entire stylesheet within the document's body and avoiding extra round trips appears to be a better thing. Obviously, caching is no longer a problem, because `<style>{style}</style>` is read from `.next/static/style.css` when your Next.js server starts.

---

If you want to check your website's performance, simply run

```bash
npm install --global lighthouse

lighthouse http://example.com/ --view
```

**Comment by bryandowning** [comment]
If you're going with the inlining approach, you may need to use:

`<style dangerouslySetInnerHTML={{ __html: style }} />`

**Comment by kachkaev** [comment]
Thank you @bryandowning! I updated the comment.

**Comment by timneutkens** [comment]
Will be possible when https://github.com/zeit/next.js/pull/4119 lands for Next 6
