### ISSUE TITLE
localIdentName support in next-css?

### ISSUE THREAD

**Issue by thekevinscott** [zeit/next-plugins#15]
Hi there,

Is `localIdentName` passable as an option to the webpack css loader? (It doesn't look like it from the code but I may be missing something).

We have a custom `localIdentName` convention that allows our designers to pass back feedback to the dev team. I'd like to get that working in our `Next.js` app.

[I put together a PR](https://github.com/zeit/next-plugins/pull/16) in case this is something that doesn't exist but would be useful.

**Comment by gihrig** [comment]
@thekevinscott I definitely have a need for this functionality, but I world prefer to do it in `postcss.config.js`.

I have been trying to figure out how to do this with next-css. I've taken the approach of using PostCSS to pass options to cssModules, which has worked well, so far.

I did it this way because I intend to use  'postcss-cssnext', in addition to 'postcss-modules' and I would rather have all of that configuration in one place.

What I have (below) works well for processing the .css, but I have yet to figure out how process the resulting html. That is, class `.hello` becomes `.styles_hello-1P9z` in the generated css, but still needs to be processed into `styles_hello-1P9z`in the generated html.

I didn't see that your modification in #16 included that final step, or did I miss something?

Here's what I have so far:

`nest.config.js`
```javascript
module.exports = withCSS({
  cssmodules: true,
  ...
})
```
`postcss.config.js`
```javascript
const cssnext = require('postcss-cssnext')
const cssModules = require('postcss-modules')

module.exports = {
  plugins: [
    cssnext(),
    cssModules({
      generateScopedName: '[name]_[local]-[hash:base64:4]',
    }),
  ],
};
```

`./styles.css`
```css
.hello {
  font: 24px Menlo, ...
```
becomes:
`./.next/static/style.css`
```css
.styles_hello-1P9z{font:24px Menlo, ...
```

This works well for 'mangling' selectors in the generated css, but doesn't change selector names in the html.

Does your solution handle the html?

**Comment by timneutkens** [comment]
As per #16 this will soon be possible using `cssLoaderOptions`
