### ISSUE TITLE
.next/static/styles.css only has one page style

### ISSUE THREAD

**Issue by davidqhr** [zeit/next-plugins#21]
I have multi pages. Each page has its own styles files included.

```javascript
// pages/a.js
import "../styles/pageA.scss"
```

```javascript
// pages/b.js
import "../styles/pageB.scss"
```

After building in production mode.
I got one file which stored at .next/static/style.css

All style of pageA.scss is missing. If I remove the `import "../styles/pageB.scss"` statement, then build. I can see the style of page a.

Is the styles.css generated multi times, and the second replace the first one. So the style of page a is missing in the end.

**Comment by jeremy-colin** [comment]
I also investigated this, here is what I think is happening: Next creates different Webpack entries for each pages and resolve common dependencies with CommonsChunkPlugin. ExtractTextPlugin then resolve every entry and overrides them as the name by default is generic.

Solution (for now) is to use your own ExtractTextPlugin with` filename: static/[name].css`

The current satisfying solutions I went for is to use   
```
filename: (getPath) =>
    `static/${getPath('[name].css')
      .replace('bundles/pages/', '')
      .replace('.js.css', '.css')}`,
```

then your dist folder will contain _next/static and your pages with [name].css, it also works for subpages.

All you have to do now is to add the corresponding file for each page, for example on login page (pages/login.js):
```
<Head>
    <link rel='stylesheet' href='/_next/static/login.css' />
</Head>
```

I think this makes sense since now each page will dynamically load its own required style

CommonChunksPlugin will also create a common.css file if you have common styles, for this you can use the recommended layout comment with 

```
<Head>
    <link rel='stylesheet' href='/_next/static/common.css' />
</Head>
```

This has been tested without next plugins (simply with a custom ExtractTextPlugin) but will be enabed for them too as soon as we can configure ExtractTextPlugin and works for both ssr and export.

I am also curious what would be next guys recommended approach to this. Note these plugins are super fresh and they made an impressive effort to make them work already (even if its only simple cases for now). Keep up the good work guys

**Comment by jeremycolin** [comment]
I also investigated this, here is what I think is happening: Next creates different Webpack entries for each pages and resolve common dependencies with CommonsChunkPlugin. ExtractTextPlugin then resolve every entry and overrides them as the name by default is generic.

Solution (for now) is to use your own ExtractTextPlugin with` filename: static/[name].css`

The current satisfying solutions I went for is to use   
```
filename: (getPath) =>
    `static/${getPath('[name].css')
      .replace('bundles/pages/', '')
      .replace('.js.css', '.css')}`,
```

then your dist folder will contain _next/static and your pages with [name].css, it also works for subpages.

All you have to do now is to add the corresponding file for each page, for example on login page (pages/login.js):
```
<Head>
    <link rel='stylesheet' href='/_next/static/login.css' />
</Head>
```

I think this makes sense since now each page will dynamically load its own required style

CommonChunksPlugin will also create a common.css file if you have common styles, for this you can use the recommended layout comment with 

```
<Head>
    <link rel='stylesheet' href='/_next/static/common.css' />
</Head>
```

This has been tested without next plugins (simply with a custom ExtractTextPlugin) but will be enabed for them too as soon as we can configure ExtractTextPlugin and works for both ssr and export.

I am also curious what would be the Next guys recommended approach to this. Note these plugins are super fresh and they made an impressive effort to make them work already (even if its only simple cases for now). Keep up the good work guys

**Comment by plag** [comment]
I've just tried merge-files-webpack-plugin with custom ExtractTextPlugin config

```
const cssFilename = 'static/css/[name].css';

const extractCSSPlugin = new ExtractTextPlugin({
  filename: cssFilename,
  allChunks: true
});

...

new MergeFilesPlugin({
  filename: 'static/style.css',
  test: /style\.css/,
  deleteSourceFiles: true,
})
```

but it's not working with same components on pages. Ex.: `import A from 'component'` on page1 and `import A from 'component'` on page2 will concatenated and you got style duplicate in common style file.

Think that need work around it.

**Comment by julmot** [comment]
There needs to be a documentation from the Next.js authors.

**Comment by plag** [comment]
Just make fast dirty fix for production builds:

`next.config.js`

```
...
    config.plugins.push(
      new MergeFilesPlugin({
        filename: 'static/style.css',
        test: /style\.css/,
        deleteSourceFiles: true,
      }),
    );
...
```


`optimize.js`
```
const fs = require('fs');
const postcss = require('postcss');
const cssnano = require('cssnano');

const src = process.argv[2];
const dst = process.argv[3];

fs.readFile(src, (err, css) => {
  postcss([cssnano])
    .process(css, { from: src, to: dst })
    .then(result => {
        fs.writeFile(dst, result.css);
        if (result.map) fs.writeFile(dst.replace(/\.css$/, '.map.css'), result.map);
    });
});
``` 

`package.json`
```
...
scripts: {
   ...
   "build": "next build && node optimize-css.js .next/static/style.css .next/static/styles.css",
   ...
}
...
```

`Layout.js`
```
...
   <Head>
   ...
      {
        isProduction && <link rel="stylesheet" href="/_next/static/styles.css" />
      }
   ...
   </Head>
...
```

and finally

`yarn build`
`yarn start`

:-) of course, i'll fix it after get right config, but good for begin. My old config with deprecated rewrited configs + one big single file was more horrendous)

**Comment by plag** [comment]
@jeremycolin thanks for your note about common chunks plugin in https://github.com/zeit/next-plugins/pull/29 
Some things for avoid make second pass compilation though cssnano. My new dirty hack in `next.config.js`: 
```
const isCssFile = /\.css$/;
const isSassFile = /\.s(c|a)ss$/;

...

  if (!isServer) {
    const pluginWithCommonChunks = config.plugins.find(function(item) {
      if (item.constructor.name !== 'CommonsChunkPlugin') {
        return false;
      }

      if (item.filenameTemplate !== 'commons.js') {
        return false;
      }

      return true;
    })

    if (pluginWithCommonChunks) {
      const originalFn = pluginWithCommonChunks.minChunks;

      pluginWithCommonChunks.minChunks = function (module, count) {
        if (isCssFile.test(module.resource) || isSassFile.test(module.resource)) {
          return count >= 2;
        }

        return originalFn(module, count);
      }
    }

    config.plugins.push(
      // extractCSSPlugin,
      new MergeFilesPlugin({
        filename: 'static/style.css',
        test: /style\.css/,
        deleteSourceFiles: true,
      }),
    );
  }

```

**Comment by timneutkens** [comment]
Will be fixed in the next release.

**Comment by goldensunliu** [comment]
@timneutkens any idea when the next release is? I am trying to submit a PR for https://github.com/zeit/next.js/issues/3701 https://github.com/zeit/next.js/issues/3700 https://github.com/zeit/next.js/issues/3699. It includes multiple pages and isn't too helpful at the moment.

**Comment by hussainb** [comment]
any update on this?

**Comment by manuquentin** [comment]
A thing that worked for me: overriding `next-css` configuration to change the `extractCSSPlugin` configuration to `filename: 'static/[name].css'`, and then merge all theses files.

`next.config.js`:
```js
const MergeFilesPlugin = require('merge-files-webpack-plugin');
// ...

webpack (config, options) {
  const {isServer } = options;
  if (!isServer) {
    // Override next-css configuration
    options.extractCSSPlugin.filename = 'static/[name].css';
    // Merge all CSS in one file
    config.plugins.push(
      new MergeFilesPlugin({
        filename: 'static/style.css',
        test: /\.css/,
        deleteSourceFiles: true,
      })
    );
  }
// ...
```

**Comment by brettdewoody** [comment]
@timneutkens I'm running into this issue on production as well. Was a fix already released?

**Comment by supadits** [comment]
Using @manuquentin solved my case
portion of My next.config.js
```javascript
const MergeFilesPlugin = require('merge-files-webpack-plugin');
const withCSS = require('@zeit/next-css')
const withSASS = require('@zeit/next-sass')

const baseConfig = {
  distDir: 'dist',
  webpack(config, options) {
    const {isServer } = options;
    //ref: https://github.com/zeit/next-plugins/issues/21 
    if (!isServer) {
      // Override next-css configuration
      options.extractCSSPlugin.filename = 'static/[name].css';
      // Merge all CSS in one file
      config.plugins.push(
        new MergeFilesPlugin({
          filename: 'static/style.css',
          test: /\.css/,
          deleteSourceFiles: true,
        })
      )
    }
    return config
  }
}

module.exports = withCSS(withSASS(baseConfig))
```

**Comment by trusktr** [comment]
My site works perfectly when I run `next`, but when I try `next build && next export`, then serve the static site, a bunch of styles are missing (bunch of things unstyled). Is this likely the same issue?

**Comment by trusktr** [comment]
You know what, I'll fix this by switching from using CSS/Sass files to using CSS-in-JS ([JSS](https://github.com/cssinjs/jss) is nice, and see [react-jss](https://github.com/cssinjs/react-jss)).

I really hope this gets officially fixed though!

**Comment by timneutkens** [comment]
@trusktr did you use `next@canary` + `@zeit/next-css@canary

**Comment by deltaepsilon** [comment]
I'm still seeing this problem. It's exactly as @trusktr described. A bunch of my CSS files aren't making to to my `out` folder.
