### ISSUE TITLE
withLess breaks dynamic component import

### ISSUE THREAD

**Issue by Kinbaum** [zeit/next-plugins#344]
I have the following component which imports a component dynamically at runtime through the use of a template literal:

```
// Importing components dynamically
import(`./${someRuntimeVariable}`).then(module => this.setState({
    module: module.default
}));
```

In my `next.config.js` I have the following:

```
const { version } = require('./package.json');

module.exports = {
    publicRuntimeConfig: {
        'process.env.ENV': process.env.ENV
    },
    generateBuildId: async () => version
};
```

This approach works well and I am able to import components dynamically at runtime. The issue however is when I try to incorporate `withLess()` into my `next.config.js` file. The following configuration will cause the dynamic import to fail:

```
const withLess = require('@zeit/next-less');
const { version } = require('./package.json');

module.exports = withLess({
    publicRuntimeConfig: {
        'process.env.ENV': process.env.ENV
    },
    generateBuildId: async () => version
});
```

The code fails and I see the follow error message being logged out to the console:

```
GET http://localhost:8080/_next/static/development/pages/test.js net::ERR_ABORTED 404 (Not Found)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
```

Can someone please offer a resolution to this issue; am I missing a configuration? For the purposes of my application, the components have to be imported dynamically as they are JSON-driven.

**Comment by MatthewKinbaum** [comment]
I have found the solution to my problem. If I don't use dynamic imports, then there is no action required on my part, my`.less` files will compile without issue. Here was the general structure:

```
- components
    - clientlibs
        - _app
            - variables.less
            - main.less
        - Button
            - default.less
        - Textfield 
            - default.less
```

Inside of my `main.less` I was importing my variables file, as well as each component like so:

```
@import (once) 'variables';
@import (once) '../Button/default';
@import (once) '../TextField/default';
```

The `Button` and `TextField` default files made references to the variables declared in `_app`. This approach works when I'm not using the dynamic import syntax. As soon as I do, this breaks. The work around is to import the `variables` into each file directly... 

Could someone please explain why that is?
Is there a what to supply a different test case to the `withLess()` module so that I only target my `_app` file, versus every file with a `.less` extension?
