### ISSUE TITLE
Deps vs DevDeps

### ISSUE THREAD

**Issue by jthegedus** [zeit/next-plugins#74]
Now that Next.js has moved to a universal webpack solution, are we forced to put our JS compilation (eg: `@zeit/next-typescript`) as a dependency instead of devDependency?

The [next-typescript package installation section](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript#installation) would indicate yes:

```
yarn add @zeit/next-typescript typescript
```

Is this correct thinking, or is the above a typo (missing `-D`) and not required as a dep?

**Comment by timneutkens** [comment]
It's needed when building the app. In theory you'd only need typescript / next-typescript when building the app.
In the next canary release (not out yet) you'll be able to use this:

https://github.com/zeit/next.js#custom-configuration

A config function to conditionally load modules per `phase`, this way you can distinguish between build / development / production / export.

I'm not planning to update this section of the readme since the provided way is required for eg now.sh deployments.
